import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#3a3a3a',
    fontFamily: 'monospace',
    marginTop: 4,
  },
  calendar: {
    borderRadius: 8,
    padding: 5,
    backgroundColor: '#f0f0f0',
  },
  selectedDate: {
    marginVertical: 8,
    fontSize: 14,
    fontFamily: 'monospace',
    color: '#333',
  },
  fabContainer: {
    flex: 1,
    position: 'absolute',
    right: 20,
    bottom: 30,
    alignItems: 'flex-end',
    paddingBottom: 90,
  },
  fab: {
    backgroundColor: '#2b8a3e',
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  fabMenu: {
    marginBottom: 10,
  },
  bubble: {
    backgroundColor: '#2b8a3e',
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  modalContent: {
    margin: 32,
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'monospace',
    marginBottom: 10,
    textAlign: 'center',
  },
  modalInput: {
    height: 120,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10,
    padding: 10,
    marginBottom: 12,
    fontFamily: 'monospace',
  },
  modalButton: {
    backgroundColor: '#2b8a3e',
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
  },
  emojiPicker: {
    backgroundColor: 'white',
    margin: 32,
    borderRadius: 16,
    padding: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  box: {
    width: 310,
    maxHeight: 210,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.5,
    elevation: 5,
    overflow: 'hidden',
    flex: 1,
  },
});
